- name: Install Java
  apt:
    name: openjdk-17-jdk
    state: present
    update_cache: yes

- name: Add Jenkins repository key
  apt_key:
    url: https://pkg.jenkins.io/debian/jenkins.io.key
    state: present

- name: Add Jenkins repository
  apt_repository:
    repo: "deb https://pkg.jenkins.io/debian-stable binary/"
    state: present

- name: Install Jenkins
  apt:
    name: jenkins
    state: present

- name: Ensure Jenkins is running
  systemd:
    name: jenkins
    enabled: yes
    state: started

- name: Allow firewall ports
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop: [22, 8080]

- name: Enable firewall
  ufw:
    state: enabled
    policy: deny
- name: Download Jenkins CLI tool
  get_url:
    url: http://localhost:8080/jnlpJars/jenkins-cli.jar
    dest: /tmp/jenkins-cli.jar

# - name: Wait for Jenkins to be up before installing plugins
#   uri:
#     url: http://localhost:8080/login
#     status_code: 200
#   register: jenkins_status
#   until: jenkins_status.status == 200
#   retries: 30
#   delay: 5

- name: Wait for Jenkins to be ready
  uri:
    url: http://localhost:8080/login
    status_code: 200
  register: jenkins_login
  until: jenkins_login.status == 200
  retries: 30
  delay: 5

- name: Create directory for init scripts
  file:
    path: /var/lib/jenkins/init.groovy.d
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0755

- name: Create default admin user
  copy:
    src: basic-security.groovy
    owner: jenkins
    group: jenkins
    mode: "0644"
    dest: /var/lib/jenkins/init.groovy.d/basic-security.groovy

- name: Set Jenkins URL
  copy:
    src: set-url.groovy
    owner: jenkins
    group: jenkins
    mode: "0644"
    dest: /var/lib/jenkins/init.groovy.d/set-url.groovy
  notify: Restart Jenkins

- name: Force Restart Jenkins to apply admin user creation
  systemd:
    name: jenkins
    state: restarted

- name: Wait for Jenkins to be ready after admin setup
  uri:
    url: http://localhost:8080/login
    status_code: 200
  register: jenkins_ready
  until: jenkins_ready.status == 200
  retries: 30
  delay: 5

- name: Copy SSH private key to controller (for agent registration)
  copy:
    src: "../../keys/jenkins-key"
    dest: "/home/ubuntu/.ssh/jenkins-key"
    owner: ubuntu
    group: ubuntu
    mode: "0600"

- name: Create .ssh directory for Jenkins user
  file:
    path: /var/lib/jenkins/.ssh
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0700

- name: Copy private key to Jenkins home
  copy:
    src: "../../keys/jenkins-key"
    dest: "/var/lib/jenkins/.ssh/id_rsa"
    owner: jenkins
    group: jenkins
    mode: "0600"

- name: Install Jenkins plugins using CLI
  shell: >
    java -jar /tmp/jenkins-cli.jar -s http://localhost:8080 -auth {{ jenkins_admin_user }}:{{ jenkins_admin_pass }} install-plugin {{ item }} -deploy
  loop:
    - ssh-slaves
    - workflow-aggregator
    - matrix-auth
    - blueocean
    - prometheus
  args:
    warn: false

- name: Deploy SSH-based agent auto-registration Groovy script
  copy:
    src: agent-ssh.groovy
    owner: jenkins
    group: jenkins
    mode: "0644"
    dest: /var/lib/jenkins/init.groovy.d/agent-ssh.groovy

- name: Create SSH credentials for agent in Jenkins (Groovy)
  copy:
    src: agent-ssh-creds.groovy
    owner: jenkins
    group: jenkins
    mode: "0644"
    dest: /var/lib/jenkins/init.groovy.d/agent-ssh-creds.groovy

  notify: Restart Jenkins

- name: Restart Jenkins to apply Groovy scripts
  systemd:
    name: jenkins
    state: restarted
